services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    working_dir: /code
    volumes:
      - ../data:/data
      - ../log:/log
      - ${AUDIO_DIR}:/srv/data
    command: uv run --with gunicorn gunicorn --bind 0.0.0.0:${PORT} --workers=${NUM_WORKERS} --timeout=800 app:server
